--DROP USER test_user@localhost;
CREATE USER test_user@localhost IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON MANAGE_DB.* TO test_user@localhost;

--DROP DATABASE MANAGE_DB;
CREATE DATABASE MANAGE_DB default CHARACTER SET UTF8;

-- Category Table
DROP TABLE IF EXISTS MANAGE_DB.CATEGORY;
CREATE TABLE IF NOT EXISTS MANAGE_DB.CATEGORY (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `TYPE` VARCHAR(50) NOT NULL,
    `TITLE` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `UPDATED_BY` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY(`ID`)
);

-- User Table
DROP TABLE IF EXISTS MANAGE_DB.USER;
CREATE TABLE IF NOT EXISTS MANAGE_DB.USER (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `ACCOUNT` VARCHAR(12) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `EMAIL` VARCHAR(100) DEFAULT NULL,
    `PHONE_NUMBER` VARCHAR(13) NOT NULL,
    `REGISTERED_AT` DATETIME DEFAULT NULL,
    `UNREGISTERED_AT` DATETIME DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `UPDATED_BY` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY(`ID`)
);

-- Partner Table
DROP TABLE IF EXISTS MANAGE_DB.PARTNER;
CREATE TABLE IF NOT EXISTS MANAGE_DB.PARTNER (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) DEFAULT NULL,
    `STATUS` VARCHAR(50) DEFAULT NULL,
    `ADDRESS` VARCHAR(100) DEFAULT NULL,
    `CALL_CENTER` VARCHAR(13) DEFAULT NULL,
    `PARTNER_NUMBER` VARCHAR(13) DEFAULT NULL,
    `BUSINESS_NUMBER` VARCHAR(16) DEFAULT NULL,
    `CEO_NAME` VARCHAR(20) DEFAULT NULL,
    `REGISTERED_AT` DATETIME DEFAULT NULL,
    `UNREGISTERED_AT` DATETIME DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `UPDATED_BY` VARCHAR(20) DEFAULT NULL,
    `CATEGORY_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY(`ID`)
);

-- Item Table
DROP TABLE IF EXISTS MANAGE_DB.ITEM;
CREATE TABLE IF NOT EXISTS MANAGE_DB.ITEM (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `STATUS` VARCHAR(50) DEFAULT NULL,
    `NAME` VARCHAR(45) NOT NULL,
    `TITLE` varchar(100) NOT NULL,
    `CONTENT` TEXT NOT NULL,
    `PRICE` DECIMAL(12,4) NOT NULL,
    `BRAND_NAME` VARCHAR(45) DEFAULT NULL,
    `REGISTERED_AT` DATETIME DEFAULT NULL,
    `UNREGISTERED_AT` DATETIME DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `UPDATED_BY` VARCHAR(20) DEFAULT NULL,
    `PARTNER_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

-- OrderDetail Table
DROP TABLE IF EXISTS MANAGE_DB.ORDER_DETAIL;
CREATE TABLE IF NOT EXISTS MANAGE_DB.ORDER_DETAIL (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `STATUS` VARCHAR(50) DEFAULT NULL,
    `ARRIVAL_DATE` DATETIME NOT NULL,
    `QUANTITY` INT(11) DEFAULT NULL,
    `TOTAL_PRICE` DECIMAL(12,4) DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `UPDATED_BY` VARCHAR(20) DEFAULT NULL,
    `ORDER_GROUP_ID` BIGINT(20) NOT NULL,
    `ITEM_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

-- OrderGroup Table
DROP TABLE IF EXISTS MANAGE_DB.ORDER_GROUP;
CREATE TABLE IF NOT EXISTS MANAGE_DB.ORDER_GROUP (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `STATUS` VARCHAR(50) DEFAULT NULL,
    `ORDER_TYPE` VARCHAR(50) NOT NULL,
    `REV_ADDRESS` VARCHAR(100) DEFAULT NULL,
    `REV_NAME` VARCHAR(50) DEFAULT NULL,
    `PAYMENT_TYPE` VARCHAR(50) DEFAULT NULL,
    `TOTAL_PRICE` DECIMAL(12,4) DEFAULT NULL,
    `TOTAL_QUANTITY` INT(11) DEFAULT NULL,
    `ORDER_AT` DATETIME DEFAULT NULL,
    `ARRIVAL_DATE` DATETIME DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `UPDATED_BY` VARCHAR(20) DEFAULT NULL,
    `USER_ID` BIGINT(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

-- AdminUser Table
DROP TABLE IF EXISTS MANAGE_DB.ADMIN_USER;
CREATE TABLE IF NOT EXISTS MANAGE_DB.ADMIN_USER (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `ACCOUNT` VARCHAR(12) NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `ROLE` VARCHAR(50) NOT NULL,
    `LAST_LOGIN_AT` DATETIME DEFAULT NULL,
    `LOGIN_FAIL_COUNT` INT(11) DEFAULT NULL,
    `PASSWORD_UPDATED_AT` DATETIME DEFAULT NULL,
    `REGISTERED_AT` DATETIME DEFAULT NULL,
    `UNREGISTERED_AT` DATETIME DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `UPDATED_BY` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`ID`)
);