--DROP USER test_user@localhost;
CREATE USER test_user@localhost IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON STUDY_DB.* TO test_user@localhost;

--DROP DATABASE STUDY_DB;
CREATE DATABASE STUDY_DB default CHARACTER SET UTF8;

--DELETE TABLE STUDY_DB.USER;
CREATE TABLE IF NOT EXISTS STUDY_DB.USER (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    ACCOUNT VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45),
    PHONE_NUMBER VARCHAR(45),
    CREATED_AT DATETIME NOT NULL,
    CREATED_BY VARCHAR(45) NOT NULL,
    UPDATED_AT DATETIME,
    UPDATED_BY VARCHAR(45),
    PRIMARY KEY(ID)
);

SELECT * FROM STUDY_DB.USER;